In [1]:
import pandas as pd
import matplotlib.pyplot as plt
# pd.set_option('display.max_rows', None)

In [304]:
year = 2023

In [ ]:

# Load the dataset
drug_df = pd.read_csv(f"yearly data/{year}/DRUG_{year}.csv")

In [274]:
# List of asthma-related drugs
asthma_drugs = [
    "Albuterol", "Salbutamol", "Levalbuterol", "Xopenex", "Symbicort", "Advair",
    "Fluticasone", "Flovent", "Flonase", "Budesonide", "Pulmicort", "Montelukast",
    "Singulair", "Ipratropium", "Combivent", "Serevent", "Qvar", "DuoNeb", "Theophylline"
]

# Filter the DataFrame for asthma-related records
asthma_related_df = drug_df[drug_df['drugname'].str.contains('|'.join(asthma_drugs), case=False, na=False)]

# Display the shape of the filtered DataFrame and a sample
print(asthma_related_df.shape)
print(asthma_related_df.head())

(141523, 20)
      primaryid    caseid  drug_seq role_cod    drugname  \
140  1014222246  10142222        18        C  ADVAIR HFA
177  1014280315  10142803        28        C   SYMBICORT
258  1023164236  10231642        10        C   SYMBICORT
269  1023181919  10231819         8        C   ALBUTEROL
345  1035338110  10353381         6        C   SYMBICORT

                                         prod_ai  val_vbm    route  dose_vbm  \
140  FLUTICASONE PROPIONATE\SALMETEROL XINAFOATE        1      NaN       NaN
177     BUDESONIDE\FORMOTEROL FUMARATE DIHYDRATE        1  Unknown       NaN
258     BUDESONIDE\FORMOTEROL FUMARATE DIHYDRATE        1      NaN  UNK, BID
269                                    ALBUTEROL        1      NaN       NaN
345     BUDESONIDE\FORMOTEROL FUMARATE DIHYDRATE        1  Unknown       UNK

     cum_dose_chr cum_dose_unit dechal rechal lot_num  exp_dt  nda_num  \
140           NaN           NaN    NaN    NaN     NaN     NaN      NaN
177           NaN           NaN      U    NaN     NaN     NaN      NaN
258           NaN           NaN      U    NaN     NaN     NaN      NaN
269           NaN           NaN    NaN    NaN     NaN     NaN      NaN
345           NaN           NaN    NaN    NaN     NaN     NaN      NaN

     dose_amt dose_unit dose_form dose_freq
140       NaN       NaN       NaN       NaN
177       NaN       NaN       NaN       NaN
258       NaN       NaN   Inhaler       BID
269       NaN       NaN       NaN       NaN
345       NaN       NaN       NaN       NaN

In [275]:
asthma_related_df.columns

Index(['primaryid', 'caseid', 'drug_seq', 'role_cod', 'drugname', 'prod_ai',
       'val_vbm', 'route', 'dose_vbm', 'cum_dose_chr', 'cum_dose_unit',
       'dechal', 'rechal', 'lot_num', 'exp_dt', 'nda_num', 'dose_amt',
       'dose_unit', 'dose_form', 'dose_freq'],
      dtype='object')

In [276]:
asthma_related_df

,primaryid,caseid,drug_seq,role_cod,drugname,prod_ai,val_vbm,route,dose_vbm,cum_dose_chr,cum_dose_unit,dechal,rechal,lot_num,exp_dt,nda_num,dose_amt,dose_unit,dose_form,dose_freq
140,1014222246,10142222,18,C,ADVAIR HFA,FLUTICASONE PROPIONATE\SALMETEROL XINAFOATE,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
177,1014280315,10142803,28,C,SYMBICORT,BUDESONIDE\FORMOTEROL FUMARATE DIHYDRATE,1,Unknown,NaN,NaN,NaN,U,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
258,1023164236,10231642,10,C,SYMBICORT,BUDESONIDE\FORMOTEROL FUMARATE DIHYDRATE,1,NaN,"UNK, BID",NaN,NaN,U,NaN,NaN,NaN,NaN,NaN,NaN,Inhaler,BID
269,1023181919,10231819,8,C,ALBUTEROL,ALBUTEROL,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
345,1035338110,10353381,6,C,SYMBICORT,BUDESONIDE\FORMOTEROL FUMARATE DIHYDRATE,1,Unknown,UNK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7473603,986902732,9869027,24,C,ALBUTEROL SULFATE,ALBUTEROL SULFATE,1,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7473604,986902732,9869027,25,C,SINGULAIR,MONTELUKAST SODIUM,1,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,MG,NaN,QD
7473628,987675338,9876753,23,C,SYMBICORT,BUDESONIDE\FORMOTEROL FUMARATE DIHYDRATE,1,Unknown,"2 DF, BID",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BID
7473669,987703850,9877038,34,C,ALBUTEROL,ALBUTEROL,1,NaN,as required,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7473705,998834884,9988348,21,C,SYMBICORT,BUDESONIDE\FORMOTEROL FUMARATE DIHYDRATE,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [277]:
# Drop duplicates
drug_df = asthma_related_df.drop_duplicates()

In [278]:
drug_df

,primaryid,caseid,drug_seq,role_cod,drugname,prod_ai,val_vbm,route,dose_vbm,cum_dose_chr,cum_dose_unit,dechal,rechal,lot_num,exp_dt,nda_num,dose_amt,dose_unit,dose_form,dose_freq
140,1014222246,10142222,18,C,ADVAIR HFA,FLUTICASONE PROPIONATE\SALMETEROL XINAFOATE,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
177,1014280315,10142803,28,C,SYMBICORT,BUDESONIDE\FORMOTEROL FUMARATE DIHYDRATE,1,Unknown,NaN,NaN,NaN,U,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
258,1023164236,10231642,10,C,SYMBICORT,BUDESONIDE\FORMOTEROL FUMARATE DIHYDRATE,1,NaN,"UNK, BID",NaN,NaN,U,NaN,NaN,NaN,NaN,NaN,NaN,Inhaler,BID
269,1023181919,10231819,8,C,ALBUTEROL,ALBUTEROL,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
345,1035338110,10353381,6,C,SYMBICORT,BUDESONIDE\FORMOTEROL FUMARATE DIHYDRATE,1,Unknown,UNK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7473603,986902732,9869027,24,C,ALBUTEROL SULFATE,ALBUTEROL SULFATE,1,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7473604,986902732,9869027,25,C,SINGULAIR,MONTELUKAST SODIUM,1,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,MG,NaN,QD
7473628,987675338,9876753,23,C,SYMBICORT,BUDESONIDE\FORMOTEROL FUMARATE DIHYDRATE,1,Unknown,"2 DF, BID",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BID
7473669,987703850,9877038,34,C,ALBUTEROL,ALBUTEROL,1,NaN,as required,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7473705,998834884,9988348,21,C,SYMBICORT,BUDESONIDE\FORMOTEROL FUMARATE DIHYDRATE,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [279]:
# Count of missing values per column
missing_values_count = drug_df.isnull().sum()

# Display the missing values
print(missing_values_count)

primaryid             0
caseid                0
drug_seq              0
role_cod              0
drugname              0
prod_ai            1811
val_vbm               0
route             69453
dose_vbm          46951
cum_dose_chr     140886
cum_dose_unit    140886
dechal            61050
rechal           136625
lot_num          118818
exp_dt           141410
nda_num          115973
dose_amt         123174
dose_unit        123174
dose_form         98410
dose_freq        117009
dtype: int64

In [280]:
demo_df = pd.read_csv(f"yearly data/{year}/DEMO_{year}.csv")

C:\Users\kaush\AppData\Local\Temp\ipykernel_11432\4050721488.py:1: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  demo_df = pd.read_csv(f"yearly data/{year}/DEMO_{year}.csv")

In [281]:
combined_df = pd.merge(demo_df, drug_df, on=["primaryid", "caseid"], how="inner")
print(combined_df.shape)

(141523, 43)

In [282]:
indi_df = pd.read_csv(f"yearly data/{year}/INDI_{year}.csv")

In [283]:
# Merge indi_df with combined_df on 'primaryid' and 'caseid'
final_combined_df = pd.merge(combined_df, indi_df, on=["primaryid", "caseid"], how="left")

# Display the final combined DataFrame
print(final_combined_df)

          primaryid    caseid  caseversion i_f_code    event_dt      mfr_dt  \
0        1014222246  10142222           46        F  20131201.0  20230315.0
1        1014222246  10142222           46        F  20131201.0  20230315.0
2        1014280315  10142803           15        F  20130101.0  20230111.0
3        1014280315  10142803           15        F  20130101.0  20230111.0
4        1014280315  10142803           15        F  20130101.0  20230111.0
...             ...       ...          ...      ...         ...         ...
5225281   998834884   9988348           84        F  20120221.0  20231207.0
5225282   998834884   9988348           84        F  20120221.0  20231207.0
5225283   998834884   9988348           84        F  20120221.0  20231207.0
5225284   998834884   9988348           84        F  20120221.0  20231207.0
5225285   998834884   9988348           84        F  20120221.0  20231207.0

         init_fda_dt    fda_dt rept_cod auth_num  ... rechal lot_num exp_dt  \
0           20140430  20230317      EXP      NaN  ...    NaN     NaN    NaN
1           20140430  20230317      EXP      NaN  ...    NaN     NaN    NaN
2           20140430  20230120      EXP      NaN  ...    NaN     NaN    NaN
3           20140430  20230120      EXP      NaN  ...    NaN     NaN    NaN
4           20140430  20230120      EXP      NaN  ...    NaN     NaN    NaN
...              ...       ...      ...      ...  ...    ...     ...    ...
5225281     20140310  20231212      EXP      NaN  ...    NaN     NaN    NaN
5225282     20140310  20231212      EXP      NaN  ...    NaN     NaN    NaN
5225283     20140310  20231212      EXP      NaN  ...    NaN     NaN    NaN
5225284     20140310  20231212      EXP      NaN  ...    NaN     NaN    NaN
5225285     20140310  20231212      EXP      NaN  ...    NaN     NaN    NaN

         nda_num dose_amt dose_unit dose_form dose_freq  indi_drug_seq  \
0            NaN      NaN       NaN       NaN       NaN            1.0
1            NaN      NaN       NaN       NaN       NaN           20.0
2            NaN      NaN       NaN       NaN       NaN            1.0
3            NaN      NaN       NaN       NaN       NaN           27.0
4            NaN      NaN       NaN       NaN       NaN           28.0
...          ...      ...       ...       ...       ...            ...
5225281      NaN      NaN       NaN       NaN       NaN           31.0
5225282      NaN      NaN       NaN       NaN       NaN           32.0
5225283      NaN      NaN       NaN       NaN       NaN           33.0
5225284      NaN      NaN       NaN       NaN       NaN           34.0
5225285      NaN      NaN       NaN       NaN       NaN           35.0

                                     indi_pt
0                       Rheumatoid arthritis
1        Product used for unknown indication
2                                     Asthma
3               Respiratory tract congestion
4        Product used for unknown indication
...                                      ...
5225281  Product used for unknown indication
5225282  Product used for unknown indication
5225283  Product used for unknown indication
5225284  Product used for unknown indication
5225285  Product used for unknown indication

[5225286 rows x 45 columns]

In [284]:
final_combined_df = final_combined_df.drop_duplicates(subset=["primaryid", "caseid"])

In [285]:
ther_df = pd.read_csv(f"yearly data/{year}/THER_{year}.csv")
ther_df.head()

    primaryid    caseid  dsg_drug_seq    start_dt      end_dt     dur dur_cod
0  1001678118  10016781             1    201201.0    201204.0     NaN     NaN
1  1001678118  10016781             4  20120327.0         NaN     NaN     NaN
2  1001678118  10016781            10  20121005.0  20200121.0  2665.0     DAY
3  1001678118  10016781            12         NaN  20200121.0     NaN     NaN
4   100270603  10027060             1  20091117.0    201302.0     3.0      YR

In [286]:
# Merge indi_df with combined_df on 'primaryid' and 'caseid'
final_combined_df = pd.merge(final_combined_df, ther_df, on=["primaryid", "caseid"], how="left")

# Display the final combined DataFrame
print(final_combined_df)

         primaryid    caseid  caseversion i_f_code    event_dt      mfr_dt  \
0       1014222246  10142222           46        F  20131201.0  20230315.0
1       1014222246  10142222           46        F  20131201.0  20230315.0
2       1014222246  10142222           46        F  20131201.0  20230315.0
3       1014222246  10142222           46        F  20131201.0  20230315.0
4       1014222246  10142222           46        F  20131201.0  20230315.0
...            ...       ...          ...      ...         ...         ...
303915   998834884   9988348           84        F  20120221.0  20231207.0
303916   998834884   9988348           84        F  20120221.0  20231207.0
303917   998834884   9988348           84        F  20120221.0  20231207.0
303918   998834884   9988348           84        F  20120221.0  20231207.0
303919   998834884   9988348           84        F  20120221.0  20231207.0

        init_fda_dt    fda_dt rept_cod auth_num  ... dose_unit dose_form  \
0          20140430  20230317      EXP      NaN  ...       NaN       NaN
1          20140430  20230317      EXP      NaN  ...       NaN       NaN
2          20140430  20230317      EXP      NaN  ...       NaN       NaN
3          20140430  20230317      EXP      NaN  ...       NaN       NaN
4          20140430  20230317      EXP      NaN  ...       NaN       NaN
...             ...       ...      ...      ...  ...       ...       ...
303915     20140310  20231212      EXP      NaN  ...       NaN       NaN
303916     20140310  20231212      EXP      NaN  ...       NaN       NaN
303917     20140310  20231212      EXP      NaN  ...       NaN       NaN
303918     20140310  20231212      EXP      NaN  ...       NaN       NaN
303919     20140310  20231212      EXP      NaN  ...       NaN       NaN

       dose_freq  indi_drug_seq               indi_pt dsg_drug_seq  \
0            NaN            1.0  Rheumatoid arthritis          1.0
1            NaN            1.0  Rheumatoid arthritis          2.0
2            NaN            1.0  Rheumatoid arthritis          3.0
3            NaN            1.0  Rheumatoid arthritis          4.0
4            NaN            1.0  Rheumatoid arthritis          5.0
...          ...            ...                   ...          ...
303915       NaN            1.0  Rheumatoid arthritis         11.0
303916       NaN            1.0  Rheumatoid arthritis         13.0
303917       NaN            1.0  Rheumatoid arthritis         14.0
303918       NaN            1.0  Rheumatoid arthritis         16.0
303919       NaN            1.0  Rheumatoid arthritis         27.0

          start_dt      end_dt    dur dur_cod
0       20130815.0  20150513.0  637.0     DAY
1       20150611.0         NaN    NaN     NaN
2       20150708.0  20161116.0  498.0     DAY
3       20161213.0  20161213.0    1.0     DAY
4       20170926.0  20171220.0   86.0     DAY
...            ...         ...    ...     ...
303915  20230525.0         NaN    NaN     NaN
303916    201202.0         NaN    NaN     NaN
303917  20210420.0  20211230.0  255.0     DAY
303918  20210420.0  20211230.0  255.0     DAY
303919  20120227.0         NaN    NaN     NaN

[303920 rows x 50 columns]

In [287]:
final_combined_df = final_combined_df.drop_duplicates(subset=["primaryid", "caseid"])

In [288]:
reac_df = pd.read_csv(f"yearly data/{year}/REAC_{year}.csv")
reac_df

          primaryid    caseid                        pt drug_rec_act
0        1001678118  10016781       Injection site mass          NaN
1        1001678118  10016781  Blood creatine increased          NaN
2        1001678118  10016781        Mobility decreased          NaN
3        1001678118  10016781         Oedema peripheral          NaN
4        1001678118  10016781  Disturbance in attention          NaN
...             ...       ...                       ...          ...
5843812   998834884   9988348             Muscle spasms          NaN
5843813   998834884   9988348           Adnexal torsion          NaN
5843814   998834884   9988348                   Pyrexia          NaN
5843815   998834884   9988348               Infertility          NaN
5843816   998834884   9988348            Diverticulitis          NaN

[5843817 rows x 4 columns]

In [289]:
# Merge reac_df with final_combined_df
final_combined_df = pd.merge(final_combined_df, reac_df, on=["primaryid", "caseid"], how="left")

# Display the result
print(final_combined_df)

         primaryid    caseid  caseversion i_f_code    event_dt      mfr_dt  \
0       1014222246  10142222           46        F  20131201.0  20230315.0
1       1014222246  10142222           46        F  20131201.0  20230315.0
2       1014222246  10142222           46        F  20131201.0  20230315.0
3       1014222246  10142222           46        F  20131201.0  20230315.0
4       1014222246  10142222           46        F  20131201.0  20230315.0
...            ...       ...          ...      ...         ...         ...
457589   998834884   9988348           84        F  20120221.0  20231207.0
457590   998834884   9988348           84        F  20120221.0  20231207.0
457591   998834884   9988348           84        F  20120221.0  20231207.0
457592   998834884   9988348           84        F  20120221.0  20231207.0
457593   998834884   9988348           84        F  20120221.0  20231207.0

        init_fda_dt    fda_dt rept_cod auth_num  ... dose_freq indi_drug_seq  \
0          20140430  20230317      EXP      NaN  ...       NaN           1.0
1          20140430  20230317      EXP      NaN  ...       NaN           1.0
2          20140430  20230317      EXP      NaN  ...       NaN           1.0
3          20140430  20230317      EXP      NaN  ...       NaN           1.0
4          20140430  20230317      EXP      NaN  ...       NaN           1.0
...             ...       ...      ...      ...  ...       ...           ...
457589     20140310  20231212      EXP      NaN  ...       NaN           1.0
457590     20140310  20231212      EXP      NaN  ...       NaN           1.0
457591     20140310  20231212      EXP      NaN  ...       NaN           1.0
457592     20140310  20231212      EXP      NaN  ...       NaN           1.0
457593     20140310  20231212      EXP      NaN  ...       NaN           1.0

                     indi_pt  dsg_drug_seq    start_dt      end_dt    dur  \
0       Rheumatoid arthritis           1.0  20130815.0  20150513.0  637.0
1       Rheumatoid arthritis           1.0  20130815.0  20150513.0  637.0
2       Rheumatoid arthritis           1.0  20130815.0  20150513.0  637.0
3       Rheumatoid arthritis           1.0  20130815.0  20150513.0  637.0
4       Rheumatoid arthritis           1.0  20130815.0  20150513.0  637.0
...                      ...           ...         ...         ...    ...
457589  Rheumatoid arthritis           1.0  20110609.0  20140227.0  994.0
457590  Rheumatoid arthritis           1.0  20110609.0  20140227.0  994.0
457591  Rheumatoid arthritis           1.0  20110609.0  20140227.0  994.0
457592  Rheumatoid arthritis           1.0  20110609.0  20140227.0  994.0
457593  Rheumatoid arthritis           1.0  20110609.0  20140227.0  994.0

       dur_cod                                 pt drug_rec_act
0          DAY              Road traffic accident          NaN
1          DAY        Oxygen saturation decreased          NaN
2          DAY  Blood pressure diastolic abnormal          NaN
3          DAY               Rheumatoid arthritis          NaN
4          DAY                            Myalgia          NaN
...        ...                                ...          ...
457589     DAY                      Muscle spasms          NaN
457590     DAY                    Adnexal torsion          NaN
457591     DAY                            Pyrexia          NaN
457592     DAY                        Infertility          NaN
457593     DAY                     Diverticulitis          NaN

[457594 rows x 52 columns]

In [290]:
final_combined_df = final_combined_df.drop_duplicates(subset=["primaryid", "caseid"])

In [291]:
outc_df = pd.read_csv(f"yearly data/{year}/OUTC_{year}.csv")

In [292]:
# Merge reac_df with final_combined_df
final_combined_df = pd.merge(final_combined_df, outc_df, on=["primaryid", "caseid"], how="left")

# Display the result
print(final_combined_df)

        primaryid    caseid  caseversion i_f_code    event_dt      mfr_dt  \
0      1014222246  10142222           46        F  20131201.0  20230315.0
1      1014222246  10142222           46        F  20131201.0  20230315.0
2      1014280315  10142803           15        F  20130101.0  20230111.0
3      1023164236  10231642           36        F  20120505.0  20230131.0
4      1023164236  10231642           36        F  20120505.0  20230131.0
...           ...       ...          ...      ...         ...         ...
86376   987675338   9876753           38        F  20170921.0  20231201.0
86377   987675338   9876753           38        F  20170921.0  20231201.0
86378   987703850   9877038           50        F  20130101.0  20231005.0
86379   998834884   9988348           84        F  20120221.0  20231207.0
86380   998834884   9988348           84        F  20120221.0  20231207.0

       init_fda_dt    fda_dt rept_cod auth_num  ... indi_drug_seq  \
0         20140430  20230317      EXP      NaN  ...           1.0
1         20140430  20230317      EXP      NaN  ...           1.0
2         20140430  20230120      EXP      NaN  ...           1.0
3         20140611  20230207      EXP      NaN  ...           1.0
4         20140611  20230207      EXP      NaN  ...           1.0
...            ...       ...      ...      ...  ...           ...
86376     20140206  20231206      EXP      NaN  ...           1.0
86377     20140206  20231206      EXP      NaN  ...           1.0
86378     20140206  20231010      EXP      NaN  ...           1.0
86379     20140310  20231212      EXP      NaN  ...           1.0
86380     20140310  20231212      EXP      NaN  ...           1.0

                    indi_pt dsg_drug_seq    start_dt      end_dt    dur  \
0      Rheumatoid arthritis          1.0  20130815.0  20150513.0  637.0
1      Rheumatoid arthritis          1.0  20130815.0  20150513.0  637.0
2                    Asthma          1.0  20120821.0         NaN    NaN
3          Carcinoid tumour          1.0  20111122.0         NaN    NaN
4          Carcinoid tumour          1.0  20111122.0         NaN    NaN
...                     ...          ...         ...         ...    ...
86376                Asthma          1.0  20110617.0         NaN    NaN
86377                Asthma          1.0  20110617.0         NaN    NaN
86378  Rheumatoid arthritis          1.0      2011.0  20140904.0    3.0
86379  Rheumatoid arthritis          1.0  20110609.0  20140227.0  994.0
86380  Rheumatoid arthritis          1.0  20110609.0  20140227.0  994.0

      dur_cod                                    pt  drug_rec_act outc_cod
0         DAY                 Road traffic accident           NaN       HO
1         DAY                 Road traffic accident           NaN       OT
2         NaN            Product availability issue           NaN       OT
3         NaN                            Depression           NaN       HO
4         NaN                            Depression           NaN       OT
...       ...                                   ...           ...      ...
86376     NaN                             Influenza           NaN       LT
86377     NaN                             Influenza           NaN       OT
86378      YR  Therapeutic product effect decreased           NaN       OT
86379     DAY                            Angioedema           NaN       HO
86380     DAY                            Angioedema           NaN       OT

[86381 rows x 53 columns]

In [293]:
final_combined_df = final_combined_df.drop_duplicates(subset=["primaryid", "caseid"])

In [294]:
rpsr_df = pd.read_csv(f"yearly data/{year}/RPSR_{year}.csv")

In [295]:
# Merge reac_df with final_combined_df
final_combined_df = pd.merge(final_combined_df, rpsr_df, on=["primaryid", "caseid"], how="left")

# Display the result
print(final_combined_df)

        primaryid    caseid  caseversion i_f_code    event_dt      mfr_dt  \
0      1014222246  10142222           46        F  20131201.0  20230315.0
1      1014280315  10142803           15        F  20130101.0  20230111.0
2      1023164236  10231642           36        F  20120505.0  20230131.0
3      1023181919  10231819           19        F  20150818.0  20230309.0
4      1035338110  10353381           10        F  20140721.0  20230223.0
...           ...       ...          ...      ...         ...         ...
68356    98639176   9863917            6        F  20020415.0  20231130.0
68357   986902732   9869027           32        F  20121008.0  20231121.0
68358   987675338   9876753           38        F  20170921.0  20231201.0
68359   987703850   9877038           50        F  20130101.0  20231005.0
68360   998834884   9988348           84        F  20120221.0  20231207.0

       init_fda_dt    fda_dt rept_cod auth_num  ...               indi_pt  \
0         20140430  20230317      EXP      NaN  ...  Rheumatoid arthritis
1         20140430  20230120      EXP      NaN  ...                Asthma
2         20140611  20230207      EXP      NaN  ...      Carcinoid tumour
3         20140612  20230322      EXP      NaN  ...                Asthma
4         20140731  20230307      EXP      NaN  ...                Asthma
...            ...       ...      ...      ...  ...                   ...
68356     20140203  20231204      EXP      NaN  ...        Duodenal ulcer
68357     20140205  20231201      EXP      NaN  ...                Asthma
68358     20140206  20231206      EXP      NaN  ...                Asthma
68359     20140206  20231010      EXP      NaN  ...  Rheumatoid arthritis
68360     20140310  20231212      EXP      NaN  ...  Rheumatoid arthritis

      dsg_drug_seq    start_dt      end_dt    dur dur_cod  \
0              1.0  20130815.0  20150513.0  637.0     DAY
1              1.0  20120821.0         NaN    NaN     NaN
2              1.0  20111122.0         NaN    NaN     NaN
3              1.0  20131106.0         NaN    NaN     NaN
4              1.0  20140616.0         NaN    NaN     NaN
...            ...         ...         ...    ...     ...
68356          1.0  20020301.0         NaN    NaN     NaN
68357          1.0  20120815.0         NaN    NaN     NaN
68358          1.0  20110617.0         NaN    NaN     NaN
68359          1.0      2011.0  20140904.0    3.0      YR
68360          1.0  20110609.0  20140227.0  994.0     DAY

                                                     pt drug_rec_act  \
0                                 Road traffic accident          NaN
1                            Product availability issue          NaN
2                                            Depression          NaN
3                                           Obstruction          NaN
4      Inappropriate schedule of product administration          NaN
...                                                 ...          ...
68356                                    Diverticulitis          NaN
68357                                  Weight increased          NaN
68358                                         Influenza          NaN
68359              Therapeutic product effect decreased          NaN
68360                                        Angioedema          NaN

       outc_cod rpsr_cod
0            HO      NaN
1            OT      NaN
2            HO      NaN
3            HO      NaN
4            OT      NaN
...         ...      ...
68356        DE      NaN
68357        HO      NaN
68358        HO      NaN
68359        OT      NaN
68360        HO      NaN

[68361 rows x 54 columns]

In [296]:
final_combined_df = final_combined_df.drop_duplicates(subset=["primaryid", "caseid"])

In [297]:
final_combined_df.shape

(68345, 54)

In [298]:
# Find duplicates
duplicates = final_combined_df[final_combined_df.duplicated(subset=["primaryid", "caseid"])]

# Count duplicates
print("Number of duplicate rows:", len(duplicates))

Number of duplicate rows: 0

In [299]:
final_combined_df['year_data'] = year

In [300]:
final_combined_df

,primaryid,caseid,caseversion,i_f_code,event_dt,mfr_dt,init_fda_dt,fda_dt,rept_cod,auth_num,...,dsg_drug_seq,start_dt,end_dt,dur,dur_cod,pt,drug_rec_act,outc_cod,rpsr_cod,year_data
0,1014222246,10142222,46,F,20131201.0,20230315.0,20140430,20230317,EXP,NaN,...,1.0,20130815.0,20150513.0,637.0,DAY,Road traffic accident,NaN,HO,NaN,2023
1,1014280315,10142803,15,F,20130101.0,20230111.0,20140430,20230120,EXP,NaN,...,1.0,20120821.0,NaN,NaN,NaN,Product availability issue,NaN,OT,NaN,2023
2,1023164236,10231642,36,F,20120505.0,20230131.0,20140611,20230207,EXP,NaN,...,1.0,20111122.0,NaN,NaN,NaN,Depression,NaN,HO,NaN,2023
3,1023181919,10231819,19,F,20150818.0,20230309.0,20140612,20230322,EXP,NaN,...,1.0,20131106.0,NaN,NaN,NaN,Obstruction,NaN,HO,NaN,2023
4,1035338110,10353381,10,F,20140721.0,20230223.0,20140731,20230307,EXP,NaN,...,1.0,20140616.0,NaN,NaN,NaN,Inappropriate schedule of product administration,NaN,OT,NaN,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68356,98639176,9863917,6,F,20020415.0,20231130.0,20140203,20231204,EXP,NaN,...,1.0,20020301.0,NaN,NaN,NaN,Diverticulitis,NaN,DE,NaN,2023
68357,986902732,9869027,32,F,20121008.0,20231121.0,20140205,20231201,EXP,NaN,...,1.0,20120815.0,NaN,NaN,NaN,Weight increased,NaN,HO,NaN,2023
68358,987675338,9876753,38,F,20170921.0,20231201.0,20140206,20231206,EXP,NaN,...,1.0,20110617.0,NaN,NaN,NaN,Influenza,NaN,HO,NaN,2023
68359,987703850,9877038,50,F,20130101.0,20231005.0,20140206,20231010,EXP,NaN,...,1.0,2011.0,20140904.0,3.0,YR,Therapeutic product effect decreased,NaN,OT,NaN,2023
68360,998834884,9988348,84,F,20120221.0,20231207.0,20140310,20231212,EXP,NaN,...,1.0,20110609.0,20140227.0,994.0,DAY,Angioedema,NaN,HO,NaN,2023

In [301]:
# Save the final DataFrame
output_path = f"yearly data/{year}/final_combined_data_{year}.csv"
final_combined_df.to_csv(output_path, index=False)
print(f"Data for {year} processed and saved successfully at {output_path}.")

Data for 2023 processed and saved successfully at yearly data/2023/final_combined_data_2023.csv.